# Generated by Django 4.2 on 2023-06-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBM_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlobField',
            new_name='BlobStorage',
        ),
    ]
