# Generated by Django 4.2 on 2023-06-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBM_plugin', '0002_rename_blobfield_blobstorage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlobStorage',
        ),
    ]
