# Generated by Django 4.2 on 2023-06-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IBM_plugin', '0003_delete_blobstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_blob', models.BinaryField()),
                ('translated_blob', models.BinaryField()),
            ],
        ),
    ]
