# Generated by Django 4.2 on 2023-06-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBM_plugin', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlobStorage',
        ),
    ]
