# Generated by Django 4.2 on 2023-06-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBM_plugin', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlobStorage',
        ),
    ]
