# Generated by Django 4.2 on 2023-06-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IBM_plugin', '0007_delete_blobstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=25)),
                ('english_input', models.CharField(max_length=300)),
                ('english_blob', models.BinaryField()),
                ('translated_blob', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
